### PR TITLE
New smoothing method for short segments

### PR DESCRIPTION
**Pull request by joeytalbot**
This replaces the existing smoothing method used in cyclestreets::journey with a new one as explained in Issue #14

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Thanks @joeytalbot will take a look!

**Comment by Robinlovelace** [comment]
Hopefully this fixes it: https://github.com/Robinlovelace/cyclestreets/commit/38ee3cc21e91c52e6d2b2ef6f732cedf3d05ece9

**Comment by Robinlovelace** [comment]
Heads-up @joeytalbot I've got a challenge for it, can it remove the 3 annoying outliers shown here while getting the rest of the routes right?: https://rpubs.com/RobinLovelace/603026

**Comment by Robinlovelace** [comment]
I'm testing it now...

**Comment by Robinlovelace** [comment]
Reproducible example, results with method1:

``` r
# Aim: test gradient calculations in CycleStreets

library(cyclestreets)

from = tmaptools::geocode_OSM("potternewton park")
to = tmaptools::geocode_OSM("university of leeds")
r = journey(from$coords, to$coords, cols = NULL, cols_extra = NULL)
mapview::mapview(r["gradient_segment"])
```



``` r


# single route ------------------------------------------------------------

# smooth unwanted high gradients
summary(r$distances)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>     9.0    48.5   122.0   197.1   186.2   771.0
summary(r$gradient_segment)
#>     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
#> 0.000000 0.007194 0.019018 0.026387 0.037812 0.111111
plot(r$distances, r$gradient_segment)

distance_cutoff = 20
gradient_cutoff = 0.1
sel = r$gradient_segment > 0.1 &
  r$distances <= distance_cutoff
summary(sel)
#>    Mode   FALSE    TRUE 
#> logical      17       1
r$gradient_segment_smooth = stplanr::route_rolling_average(r$gradient_segment)
r$gradient_segment[sel]
#> [1] 0.1111111
r$gradient_segment_smooth[sel]
#> [1] 0.05731033

# r$gradient_segment[sel] = r$gradient_segment_smooth[sel]

plot(r$distances, r$gradient_segment)
```



``` r
mapview::mapview(r["gradient_segment"])
```



``` r

smooth_with_cutoffs = function(
  gradient_segment,
  distances,
  distance_cutoff = 20,
  gradient_cutoff = 0.1
  ) {
  sel = gradient_segment > 0.1 &
    distances <= distance_cutoff
  summary(sel)
  gradient_segment_smooth = stplanr::route_rolling_average(gradient_segment)
  gradient_segment[sel]
  gradient_segment_smooth[sel]

  gradient_segment[sel] = gradient_segment_smooth[sel]
  gradient_segment

}

r$gradient_segment
#>  [1] 0.051282051 0.015564202 0.005128205 0.007797271 0.006993007 0.057142857
#>  [7] 0.029569892 0.111111111 0.031250000 0.030769231 0.022471910 0.000000000
#> [13] 0.014388489 0.040000000 0.040000000 0.011494253 0.000000000 0.000000000
smooth_with_cutoffs(gradient_segment = r$gradient_segment, distances = r$distances)
#>  [1] 0.051282051 0.015564202 0.005128205 0.007797271 0.006993007 0.057142857
#>  [7] 0.029569892 0.057310335 0.031250000 0.030769231 0.022471910 0.000000000
#> [13] 0.014388489 0.040000000 0.040000000 0.011494253 0.000000000 0.000000000

# chapeltown dataset ------------------------------------------------------

library(stplanr)
l = od2line(od_data_sample, cents_sf)
r = route(l = l, route_fun = cyclestreets::journey, smooth_gradient = TRUE)
#> Most common output is sf
#> These routes failed: 1, 10, 19, 28, 37, 46, 55, 64
#> The first of which was:
#> <simpleError in FUN(ldf[i, 1:2], ldf[i, 3:4], ...): Error: Too short: journeys must be longer than 4 metres. (Your requested journey was 0 metres).>
#> Loading required namespace: data.table
nrow(l)
#> [1] 64
nrow(r)
#> [1] 750
length(unique(r$route_number)) # omits routes with zero length
#> [1] 56
plot(r)
#> Warning: plotting the first 10 out of 33 attributes; use max.plot = 33 to plot
#> all
```



``` r
mapview::mapview(r["gradient_smooth"])
```



``` r
mapview::mapview(r[r$gradient_smooth > 0.1, "gradient_smooth"])
```



<sup>Created on 2020-04-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
Results on new branch: 

``` r
# Aim: test gradient calculations in CycleStreets

remotes::install_github("joeytalbot/cyclestreets")
#> Using github PAT from envvar GITHUB_PAT
#> Skipping install of 'cyclestreets' from a github remote, the SHA1 (a643e30d) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(cyclestreets)

from = tmaptools::geocode_OSM("potternewton park")
to = tmaptools::geocode_OSM("university of leeds")
r = journey(from$coords, to$coords, cols = NULL, cols_extra = NULL)
mapview::mapview(r["gradient_segment"])
```



``` r


# single route ------------------------------------------------------------

# smooth unwanted high gradients
summary(r$distances)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>     9.0    48.5   122.0   197.1   186.2   771.0
summary(r$gradient_segment)
#>     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
#> 0.000000 0.007194 0.019018 0.026387 0.037812 0.111111
plot(r$distances, r$gradient_segment)

distance_cutoff = 20
gradient_cutoff = 0.1
sel = r$gradient_segment > 0.1 &
  r$distances <= distance_cutoff
summary(sel)
#>    Mode   FALSE    TRUE 
#> logical      17       1
r$gradient_segment_smooth = stplanr::route_rolling_average(r$gradient_segment)
r$gradient_segment[sel]
#> [1] 0.1111111
r$gradient_segment_smooth[sel]
#> [1] 0.05731033

# r$gradient_segment[sel] = r$gradient_segment_smooth[sel]

plot(r$distances, r$gradient_segment)
```



``` r
mapview::mapview(r["gradient_segment"])
```



``` r

smooth_with_cutoffs = function(
  gradient_segment,
  distances,
  distance_cutoff = 20,
  gradient_cutoff = 0.1
  ) {
  sel = gradient_segment > 0.1 &
    distances <= distance_cutoff
  summary(sel)
  gradient_segment_smooth = stplanr::route_rolling_average(gradient_segment)
  gradient_segment[sel]
  gradient_segment_smooth[sel]

  gradient_segment[sel] = gradient_segment_smooth[sel]
  gradient_segment

}

r$gradient_segment
#>  [1] 0.051282051 0.015564202 0.005128205 0.007797271 0.006993007 0.057142857
#>  [7] 0.029569892 0.111111111 0.031250000 0.030769231 0.022471910 0.000000000
#> [13] 0.014388489 0.040000000 0.040000000 0.011494253 0.000000000 0.000000000
smooth_with_cutoffs(gradient_segment = r$gradient_segment, distances = r$distances)
#>  [1] 0.051282051 0.015564202 0.005128205 0.007797271 0.006993007 0.057142857
#>  [7] 0.029569892 0.057310335 0.031250000 0.030769231 0.022471910 0.000000000
#> [13] 0.014388489 0.040000000 0.040000000 0.011494253 0.000000000 0.000000000

# chapeltown dataset ------------------------------------------------------

library(stplanr)
l = od2line(od_data_sample, cents_sf)
r = route(l = l, route_fun = cyclestreets::journey, smooth_gradient = TRUE)
#> Most common output is sf
#> These routes failed: 1, 10, 19, 28, 37, 46, 55, 64
#> The first of which was:
#> <simpleError in FUN(ldf[i, 1:2], ldf[i, 3:4], ...): Error: Too short: journeys must be longer than 4 metres. (Your requested journey was 0 metres).>
#> Loading required namespace: data.table
nrow(l)
#> [1] 64
nrow(r)
#> [1] 750
length(unique(r$route_number)) # omits routes with zero length
#> [1] 56
plot(r)
#> Warning: plotting the first 10 out of 34 attributes; use max.plot = 34 to plot
#> all
```



``` r
mapview::mapview(r["gradient_smooth"])
```



``` r
mapview::mapview(r[r$gradient_smooth > 0.1, "gradient_smooth"])
```



<sup>Created on 2020-04-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
OK they are too long:

```
summary(r$distances[r$gradient_smooth > 0.1])
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  24.00   67.00   67.00   82.35   67.00  143.00 
```

**Comment by Robinlovelace** [comment]
Here's a single route:

image

Here it is in Google: 

image


Interesting that they are different. I'm not sure the steep section highlighted in blue in the CycleStreets route is accurate but may be due to differences in the route I'm not aware of.

Heads-up @mvl22. Not critiquing the elevations but wondering if you have done external testing on the elevation/gradient estimates.

**Comment by Robinlovelace** [comment]
Thinking of generating external elevation profiles, e.g. using this technique: https://gis.stackexchange.com/questions/273440/calculate-slope-of-line-segments-with-qgis

**Comment by Robinlovelace** [comment]
Or even this one, which was written by @Nowosad : https://geocompr.robinlovelace.net/geometric-operations.html#raster-extraction

image


An example of where something in our book that I'd never tested may be useful for our own research!

**Comment by Robinlovelace** [comment]
Quick question for @nowosad, would this be how you recommend doing it, or is an equivalent faster `xyFromCell()` function available in `terra`/`stars` #geocompr in the wild!

**Comment by Robinlovelace** [comment]
Just realised I was putting all this in a closed PR. Please reply here: https://github.com/Robinlovelace/cyclestreets/issues/14

**Comment by Robinlovelace** [comment]
Update: here's the same area with open 1m LIDAR data in the background: 
image

**Comment by Robinlovelace** [comment]
Source: https://environment.data.gov.uk/spatialdata/lidar-composite-digital-surface-model-dsm-1m/wms

**Comment by Robinlovelace** [comment]
1m res data associated with study area:

https://environment.data.gov.uk/UserDownloads/interactive/2133d5bf5cd343daaf703ab8fb3b55d98628/LIDARCOMP/LIDAR-DTM-2M-SE23ne.zip

https://environment.data.gov.uk/UserDownloads/interactive/2133d5bf5cd343daaf703ab8fb3b55d98628/LIDARCOMP/LIDAR-DTM-2M-SE23se.zip

https://environment.data.gov.uk/UserDownloads/interactive/2133d5bf5cd343daaf703ab8fb3b55d98628/LIDARCOMP/LIDAR-DTM-2M-SE33nw.zip

https://environment.data.gov.uk/UserDownloads/interactive/2133d5bf5cd343daaf703ab8fb3b55d98628/LIDARCOMP/LIDAR-DTM-2M-SE33sw.zip

**Comment by Nowosad** [comment]
> Quick question for @Nowosad, would this be how you recommend doing it, or is an equivalent faster `xyFromCell()` function available in `terra`/`stars` #geocompr in the wild!

Nothing in **stars**. I do not know about **terra**. You can also check Rcpp functions in **landscapemetrics** - https://github.com/r-spatialecology/landscapemetrics/blob/master/src/rcpp_create_neighborhood.cpp#L15

**Pull request merged**
